version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2-amd64
    env_file:
      - elasticsearch.env
    networks:
      - esnet
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    env_file:
      - kibana.env
    ports:
      - 5601:5601

  python:
    # image: myimage
    # image: app-image
    build: .
    command: python elasticsearch_index_creation.py
    depends_on:
      - elasticsearch
    networks:
      - esnet
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    # build:
    #   # context: myapp
    #   dockerfile: Dockerfile

networks:
  esnet: